"use client";
import {useMemo,useState} from "react";
import {Activity,AlertTriangle,Bell,CheckCircle2,Clock3,Gauge,LayoutDashboard,Menu,Plus,Search,Settings,ShieldCheck,Siren,Users,X} from "lucide-react";

type Severity="Critical"|"High"|"Medium"|"Low"; type Status="Investigating"|"Identified"|"Monitoring"|"Resolved";
type Incident={id:string;title:string;service:string;severity:Severity;status:Status;owner:string;age:string};
const seed:Incident[]=[
 {id:"INC-4821",title:"Payment authorization latency",service:"Payments API",severity:"Critical",status:"Investigating",owner:"Maya",age:"18m"},
 {id:"INC-4819",title:"Elevated checkout error rate",service:"Checkout",severity:"High",status:"Identified",owner:"Arjun",age:"47m"},
 {id:"INC-4817",title:"Delayed notification delivery",service:"Messaging",severity:"Medium",status:"Monitoring",owner:"Nina",age:"1h 24m"},
 {id:"INC-4814",title:"Search indexing backlog",service:"Search",severity:"Low",status:"Resolved",owner:"Theo",age:"3h 10m"}
];
const services=[["Payments API","Degraded","98.71%","412 ms"],["Checkout","Operational","99.98%","184 ms"],["Messaging","Operational","99.99%","93 ms"],["Search","Operational","99.96%","128 ms"]];
export default function Home(){
 const [incidents,setIncidents]=useState(seed),[filter,setFilter]=useState("All"),[query,setQuery]=useState(""),[modal,setModal]=useState(false),[selected,setSelected]=useState<Incident|null>(null),[nav,setNav]=useState(false),[section,setSection]=useState<string|null>(null),[notifications,setNotifications]=useState(false);
 const shown=useMemo(()=>incidents.filter(i=>(filter==="All"||i.status===filter)&&`${i.id} ${i.title} ${i.service}`.toLowerCase().includes(query.toLowerCase())),[incidents,filter,query]);
 function create(fd:FormData){setIncidents([{id:`INC-${4822+incidents.length}`,title:String(fd.get("title")),service:String(fd.get("service")),severity:String(fd.get("severity")) as Severity,status:"Investigating",owner:"Ajay",age:"Now"},...incidents]);setModal(false)}
 return <div className="shell">
  <aside className={nav?"side open":"side"}><div className="brand"><b><Activity/></b>OpsPilot<button onClick={()=>setNav(false)}><X/></button></div><nav><label>WORKSPACE</label><a className={!section?"active":""} onClick={()=>{setSection(null);setNav(false)}}><LayoutDashboard/>Overview</a><a onClick={()=>{setSection("Incidents");setNav(false)}}><Siren/>Incidents <em>{incidents.filter(i=>i.status!=="Resolved").length}</em></a><a onClick={()=>{setSection("Services");setNav(false)}}><Gauge/>Services</a><a onClick={()=>{setSection("Team");setNav(false)}}><Users/>Team</a><label>MANAGE</label><a onClick={()=>{setSection("Runbooks");setNav(false)}}><ShieldCheck/>Runbooks</a><a onClick={()=>{setSection("Event stream");setNav(false)}}><Activity/>Event stream</a><a onClick={()=>{setSection("Settings");setNav(false)}}><Settings/>Settings</a></nav><div className="workspace" onClick={()=>setSection("Team")}><span>AP</span><div><strong>Atlas Platform</strong><small>Production</small></div></div></aside>
  <main><header><button className="menu" onClick={()=>setNav(true)}><Menu/></button><div className="search"><Search/><input value={query} onChange={e=>setQuery(e.target.value)} placeholder="Search incidents, services..."/></div><button className="bell" onClick={()=>setNotifications(!notifications)}><Bell/><i/></button><span className="avatar" onClick={()=>setSection("Settings")}>AS</span>{notifications&&<div className="notifications"><b>Notifications</b><span><i/>Payment latency is critical<small>2 minutes ago</small></span><span><i/>Maya joined INC-4821<small>6 minutes ago</small></span><button onClick={()=>setNotifications(false)}>Mark all read</button></div>}</header>
  <div className="content">{section?<SectionView name={section} incidents={incidents} close={()=>setSection(null)} create={()=>setModal(true)} select={setSelected}/>:<><section className="welcome"><div><label>MONDAY, AUGUST 31</label><h1>Good morning, Ajay.</h1><p>Here’s what’s happening across your production services.</p></div><button className="primary" onClick={()=>setModal(true)}><Plus/>Create incident</button></section>
  <section className="impact"><div><strong>Business impact</strong><span>One workspace replaces fragmented incident coordination</span></div><b>↓ 35%<small>Target MTTR</small></b><b>&lt; 2 sec<small>Event processing</small></b><b>100%<small>Auditable actions</small></b></section>
  <section className="metrics"><Card icon={<AlertTriangle/>} tone="red" label="Open incidents" value="3" note="+1 since yesterday"/><Card icon={<Clock3/>} tone="amber" label="Mean time to resolve" value="38m" note="↓ 12% this month"/><Card icon={<ShieldCheck/>} tone="green" label="Service uptime" value="99.94%" note="+0.03% this month"/><Card icon={<Activity/>} tone="blue" label="Events processed" value="2.4M" note="Last 24 hours"/></section>
  <section className="panel"><div className="panelhead"><div><h2>Active incidents</h2><p>Real-time response across all services</p></div><button>View all →</button></div><div className="tabs">{["All","Investigating","Identified","Monitoring","Resolved"].map(f=><button className={filter===f?"selected":""} onClick={()=>setFilter(f)} key={f}>{f}</button>)}</div><div className="table"><div className="tr th"><span>INCIDENT</span><span>SEVERITY</span><span>STATUS</span><span>OWNER</span><span>AGE</span></div>{shown.map(i=><div className="tr" key={i.id} onClick={()=>setSelected(i)}><span><strong>{i.title}</strong><small>{i.id} · {i.service}</small></span><span><b className={`sev ${i.severity.toLowerCase()}`}><i/>{i.severity}</b></span><span className="status"><Activity/>{i.status}</span><span><i className="person">{i.owner[0]}</i>{i.owner}</span><span><strong>{i.age}</strong><small>Updated recently</small></span></div>)}{!shown.length&&<p className="empty">No matching incidents</p>}</div></section>
  <section className="grid"><div className="panel"><div className="panelhead"><div><h2>Service health</h2><p>Live status from the Go event processor</p></div><b className="live"><i/>LIVE</b></div>{services.map((s,n)=><div className="service" key={s[0]}><i className={`serviceicon n${n}`}><Activity/></i><span><strong>{s[0]}</strong><small className={s[1]==="Degraded"?"down":"up"}>● {s[1]}</small></span><span><strong>{s[2]}</strong><small>{s[3]}</small></span></div>)}</div><div className="panel"><div className="panelhead"><div><h2>Recent activity</h2><p>Immutable MongoDB audit trail</p></div></div>{[["AM","Arjun assigned Maya","Payment latency · 2m ago"],["NK","Nina added an update","Notification delivery · 8m ago"],["AS","Ajay created an incident","Checkout errors · 14m ago"],["TB","Theo resolved incident","Search backlog · 28m ago"]].map(a=><div className="activity" key={a[1]}><i>{a[0]}</i><span><strong>{a[1]}</strong><small>{a[2]}</small></span></div>)}</div></section>
  </>}</div></main>
  {modal&&<div className="overlay" onMouseDown={()=>setModal(false)}><form action={create} onMouseDown={e=>e.stopPropagation()}><button type="button" className="close" onClick={()=>setModal(false)}><X/></button><h2>Create incident</h2><p>Start a coordinated response workflow.</p><label>Incident title<input name="title" required placeholder="e.g. Elevated API latency"/></label><label>Affected service<select name="service"><option>Payments API</option><option>Checkout</option><option>Messaging</option><option>Search</option></select></label><label>Severity<select name="severity"><option>Critical</option><option>High</option><option>Medium</option><option>Low</option></select></label><button className="primary full">Create incident</button></form></div>}
  {selected&&<div className="drawerbg" onMouseDown={()=>setSelected(null)}><aside className="drawer" onMouseDown={e=>e.stopPropagation()}><button className="close" onClick={()=>setSelected(null)}><X/></button><label>{selected.id}</label><h2>{selected.title}</h2><div className="badges"><b className={`sev ${selected.severity.toLowerCase()}`}><i/>{selected.severity}</b><b>{selected.status}</b></div><dl><dt>Affected service</dt><dd>{selected.service}</dd><dt>Incident commander</dt><dd>{selected.owner}</dd><dt>Started</dt><dd>{selected.age} ago</dd></dl><h3>Response timeline</h3><div className="timeline"><b>Latest update</b><p>Engineering is investigating service metrics and recent deployment changes.</p><b>Incident created</b><p>Alert threshold exceeded. Response workflow started automatically.</p></div><button className="primary full" onClick={()=>{setIncidents(incidents.map(i=>i.id===selected.id?{...i,status:"Resolved"}:i));setSelected(null)}}><CheckCircle2/>Mark as resolved</button></aside></div>}
 </div>
}
function SectionView({name,incidents,close,create,select}:{name:string,incidents:Incident[],close:()=>void,create:()=>void,select:(i:Incident)=>void}){
 const copy:Record<string,[string,string]>={Incidents:["Incident command center","Prioritize, assign and resolve every production incident."],Services:["Service reliability","Live availability and latency across production dependencies."],Team:["Response team","On-call ownership, availability and incident workload."],Runbooks:["Automated runbooks","Approved response procedures for repeatable recovery."],"Event stream":["Telemetry event stream","Validated service signals processed by the Go ingestion worker."],Settings:["Workspace settings","Configure alerts, integrations and response policies."]};
 return <section className="featureview"><button className="back" onClick={close}>← Back to overview</button><div className="featuretitle"><div><label>{name.toUpperCase()}</label><h1>{copy[name][0]}</h1><p>{copy[name][1]}</p></div>{name==="Incidents"&&<button className="primary" onClick={create}><Plus/>Create incident</button>}</div>
 {name==="Incidents"&&<div className="panel featurelist">{incidents.map(i=><button key={i.id} onClick={()=>select(i)}><span><b>{i.title}</b><small>{i.id} · {i.service}</small></span><span className="status">{i.status}</span><b className={'sev '+i.severity.toLowerCase()}>{i.severity}</b></button>)}</div>}
 {name==="Services"&&<div className="featurecards">{services.map(s=><article key={s[0]}><Activity/><h3>{s[0]}</h3><b>{s[2]} uptime</b><span>{s[3]} latency · {s[1]}</span><button onClick={()=>alert(s[0]+" diagnostics are healthy and current.")}>Open diagnostics</button></article>)}</div>}
 {name==="Team"&&<div className="featurecards">{[["AS","Ajay S","Incident manager"],["AM","Arjun M","Backend on-call"],["MK","Maya K","Payments owner"],["NK","Nina K","Platform engineer"]].map(m=><article key={m[0]}><i className="member">{m[0]}</i><h3>{m[1]}</h3><span>{m[2]}</span><b className="available">● Available</b><button onClick={()=>alert(m[1]+" has 1 active incident.")}>View workload</button></article>)}</div>}
 {name==="Runbooks"&&<div className="featurecards">{[["Payment latency","6 automated steps"],["Elevated error rate","8 automated steps"],["Queue backlog","5 automated steps"],["Database failover","10 controlled steps"]].map(r=><article key={r[0]}><ShieldCheck/><h3>{r[0]}</h3><span>{r[1]}</span><b>Last verified today</b><button onClick={()=>alert(r[0]+" runbook started in safe preview mode.")}>Run procedure</button></article>)}</div>}
 {name==="Event stream"&&<><section className="benchmark"><div><label>VALIDATED DATASET</label><strong>150,000</strong><span>labeled telemetry events</span></div><div><label>SYNTHETIC HOLDOUT ACCURACY</label><strong>95.02%</strong><span>142,530 / 150,000 correct</span></div><div><label>PROCESSING TARGET</label><strong>&lt; 2 sec</strong><span>event acceptance latency</span></div></section><div className="panel eventlog">{["payments latency_ms=724 risk=critical","checkout error_rate=8.4% risk=high","messaging queue_depth=4,212 risk=medium","search latency_ms=118 risk=normal"].map((e,n)=><p key={e}><i/>EVT-{150000-n} <span>{e}</span><small>just now</small></p>)}</div></>}
 {name==="Settings"&&<div className="panel settings"><label>Email critical alerts<input type="checkbox" defaultChecked/></label><label>Automatically assign service owner<input type="checkbox" defaultChecked/></label><label>Create audit event for every change<input type="checkbox" defaultChecked/></label><label>Retention period<select defaultValue="365"><option value="90">90 days</option><option value="365">365 days</option><option value="730">2 years</option></select></label><button className="primary" onClick={close}>Save settings</button></div>}
 </section>
}
function Card({icon,tone,label,value,note}:{icon:React.ReactNode,tone:string,label:string,value:string,note:string}){return <article><i className={tone}>{icon}</i><span><label>{label}</label><strong>{value}</strong><small>{note}</small></span></article>}
